### ISSUE TITLE
Version 1.6.0 Pre Info

### ISSUE THREAD

**Issue by Nisbo** [Nisbo/another_mvg#10]
Currently I am working on version 1.6.0
A Beta including screenshots is already
https://github.com/Nisbo/another_mvg/releases/tag/v1.6.0.BETA.2

**Comment by spaceboots23** [comment]
Looking good, please consider adding a configuration field for show destinations, with the opposite functionality of the already existing hidedestinations configuration field.

Example usecase: show all regional trains from Ostbahnhof to Hauptbahnhof. Without this, the user would have to hide every regional train that does not have destination hauptbahnhof.

**Comment by spaceboots23** [comment]
Also, it seems that field names are missing from V1.6.0:B2 when running HA core: 2024.8.3 frontend: 20240809.0

![Screenshot from 2024-09-04 15-16-05](https://github.com/user-attachments/assets/b7760eb5-66ff-496f-b588-e479bb0cd417)

**Comment by Nisbo** [comment]
> Looking good, please consider adding a configuration field for show destinations, with the opposite functionality of the already existing hide destinations configuration field.
> 
> Example usecase: show all regional trains from Ostbahnhof to Hauptbahnhof. Without this, the user would have to hide every regional train that does not have destination hauptbahnhof.

Good idea. But keep in mind, if for instance the train does not end on Hauptbahnhof (like S3 to Mammendorf) you will not see the connection. You have to add every possible end station. I will have a look on it.

**Comment by Nisbo** [comment]
> Also, it seems that field names are missing from V1.6.0:B2 when running HA core: 2024.8.3 frontend: 20240809.0
> 
> ![Screenshot from 2024-09-04 15-16-05](https://private-user-images.githubusercontent.com/103315269/364391064-b7760eb5-66ff-496f-b588-e479bb0cd417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTg0NDIsIm5iZiI6MTcyNTQ1ODE0MiwicGF0aCI6Ii8xMDMzMTUyNjkvMzY0MzkxMDY0LWI3NzYwZWI1LTY2ZmYtNDk2Zi1iNTg4LWU0NzliYjBjZDQxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMzU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjNlYTJmYmFlNjliOTgwYjlhNWNmZjA1NmIwMTQ2Nzk1YjU1MTljYmFmMDljNzk1OGU5OTc4NTUwYTdiZmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iZR2klAKwu9ZLVSA95X236jCMo_raQGwPFJX4LZTUUI)

Looks like this file is missing
https://github.com/Nisbo/another_mvg/blob/v1.6.0-BETA-2/custom_components/another_mvg/translations/en.json
or maybe I forgot to update something on git

**Comment by spaceboots23** [comment]
> > Looking good, please consider adding a configuration field for show destinations, with the opposite functionality of the already existing hide destinations configuration field.
> > Example usecase: show all regional trains from Ostbahnhof to Hauptbahnhof. Without this, the user would have to hide every regional train that does not have destination hauptbahnhof.
> 
> Good idea. But keep in mind, if for instance the train does not end on Hauptbahnhof (like S3 to Mammendorf) you will not see the connection. You have to add every possible end station. I will have a look on it.

Yes, this is the problem I'm trying to solve: being able to filter for connections that stop at a particular station, but don't necessarily terminate there. Basically what I'd like to achieve is some sort of Stammstrecke funcitonality, where for any given station you can easily see what the next train to the city is. Which is achievable with the negative filtering, but would be much quicker to setup with a positive filter (and be more catch all).

Either way, nice work on the integration, it's great!

**Comment by spaceboots23** [comment]
> > Also, it seems that field names are missing from V1.6.0:B2 when running HA core: 2024.8.3 frontend: 20240809.0
> > ![Screenshot from 2024-09-04 15-16-05](https://private-user-images.githubusercontent.com/103315269/364391064-b7760eb5-66ff-496f-b588-e479bb0cd417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NTg0NDIsIm5iZiI6MTcyNTQ1ODE0MiwicGF0aCI6Ii8xMDMzMTUyNjkvMzY0MzkxMDY0LWI3NzYwZWI1LTY2ZmYtNDk2Zi1iNTg4LWU0NzliYjBjZDQxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNFQxMzU1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjNlYTJmYmFlNjliOTgwYjlhNWNmZjA1NmIwMTQ2Nzk1YjU1MTljYmFmMDljNzk1OGU5OTc4NTUwYTdiZmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iZR2klAKwu9ZLVSA95X236jCMo_raQGwPFJX4LZTUUI)
> 
> Looks like this file is missing https://github.com/Nisbo/another_mvg/blob/v1.6.0-BETA-2/custom_components/another_mvg/translations/en.json or maybe I forgot to update something on git

Replacing the existing `en.json` file with the linked file has no effect on the missing labels.

**Comment by Nisbo** [comment]
> > > Looking good, please consider adding a configuration field for show destinations, with the opposite functionality of the already existing hide destinations configuration field.
> > > Example usecase: show all regional trains from Ostbahnhof to Hauptbahnhof. Without this, the user would have to hide every regional train that does not have destination hauptbahnhof.
> > 
> > 
> > Good idea. But keep in mind, if for instance the train does not end on Hauptbahnhof (like S3 to Mammendorf) you will not see the connection. You have to add every possible end station. I will have a look on it.
> 
> Yes, this is the problem I'm trying to solve: being able to filter for connections that stop at a particular station, but don't necessarily terminate there. Basically what I'd like to achieve is some sort of Stammstrecke funcitonality, where for any given station you can easily see what the next train to the city is. Which is achievable with the negative filtering, but would be much quicker to setup with a positive filter (and be more likely to catch all connections).
> 
> I'm guessing this might be due to an API limmitation?
> 
> Either way, nice work on the integration, it's great!

You are right, in the API there is no functionallity for "stadteinwärts" or something like that. This was the reason why I created the "hidestation feature". However, I think I can implement your request.

**Comment by spaceboots23** [comment]
> > > > Looking good, please consider adding a configuration field for show destinations, with the opposite functionality of the already existing hide destinations configuration field.
> > > > Example usecase: show all regional trains from Ostbahnhof to Hauptbahnhof. Without this, the user would have to hide every regional train that does not have destination hauptbahnhof.
> > > 
> > > 
> > > Good idea. But keep in mind, if for instance the train does not end on Hauptbahnhof (like S3 to Mammendorf) you will not see the connection. You have to add every possible end station. I will have a look on it.
> > 
> > 
> > Yes, this is the problem I'm trying to solve: being able to filter for connections that stop at a particular station, but don't necessarily terminate there. Basically what I'd like to achieve is some sort of Stammstrecke funcitonality, where for any given station you can easily see what the next train to the city is. Which is achievable with the negative filtering, but would be much quicker to setup with a positive filter (and be more likely to catch all connections).
> > I'm guessing this might be due to an API limmitation?
> > Either way, nice work on the integration, it's great!
> 
> You are right, in the API there is no functionallity for "stadteinwärts" or something like that. This was the reason why I created the "hidestation feature". However, I think I can implement your request.

Sounds good, I have some time in the next few weeks, so if I can wrap my head around your code I'll have a look too.

**Comment by Nisbo** [comment]
Your request regarding the destinations was implemented locally 

![grafik](https://github.com/user-attachments/assets/3cf20b33-2cb7-4096-954d-a70f08be6698)

**Comment by Nisbo** [comment]
1.6.0.BETA.3 released
https://github.com/Nisbo/another_mvg/releases/tag/v1.6.0-BETA-3-RELEASE

**Comment by Nisbo** [comment]
v1.6.0 was released as v2.0.0
https://github.com/Nisbo/another_mvg/releases/tag/v2.0.0
