### ISSUE TITLE
API is DOWN

### ISSUE THREAD

**Issue by Nisbo** [Nisbo/another_mvg#14]
Looks like the API is down. Not sure if they shut down the API or changed only the URL.
I try to get in contact with MVG

**Comment by mhelff** [comment]
Replace base URL by:
URL = "https://www.mvg.de/api/bgw-pt/v3/departures?globalId={}&limit=80&transportTypes={}

**Comment by mhelff** [comment]
Open website and take a look with the developer tools what XHR-Requests are send. There might be other changes but a quick test in my HA instance works as expected.
Can open a PR this evening, but feel free to fix it immediately

**Comment by Nisbo** [comment]
Its fixed and v1.5.1 is released
