### ISSUE TITLE
Feature request: Add time on the MVG card

### ISSUE THREAD

**Issue by Dekyi** [Nisbo/another_mvg#16]
Erstmal vielen Dank für deine Arbeit. Ich habe die Version 2.0 gerade installiert und es klappt prima. Ich baue mir da jetzt eine Anzeige für die Kinder draus. Hilfreich wäre da eine Info zur aktuellen Uhrzeit. Dann muss man das nicht extra bauen sondern hat es gleich in der MVG Anzeige. Oder habe ich die Option dafür irgendwo übersehen und das gibt es schon?

**Comment by Nisbo** [comment]
Servus,
also die Integration selbst hat keine eingebaute Uhr, aber Homeassistant selbst kann ja die Uhrzeit anzeigen.
Wie willst Du denn die Anzeige umsetzen ? Im Browser/App als Karte ? Oder auf einem externen Display wie OpenmHASP oder eine ESP Lösung ? Letzteres geht sowieso nur mit zusätzlicher Programmiererei. 

Ich habe bei mir so die Uhrzeit ins WallPanel eingebaut, mit einer ```custom:vertical-stack-in-card``` und dann mit ```markdown``` Karten

```
type: custom:vertical-stack-in-card
cards:
  - type: markdown
    triggers_update:
      - sensor.time
    content: |
      {{ now().strftime('%H:%M') }}
  - type: markdown
    triggers_update:
      - sensor.time
    content: >
      {% set wochenTage = {
        "Monday": "Montag",
        "Tuesday": "Dienstag",
        "Wednesday": "Mittwoch",
        "Thursday": "Donnerstag",
        "Friday": "Freitag",
        "Saturday": "Samstag",
        "Sunday": "Sonntag"
      } %}

      {% set monate = {
        "January": "Januar",
        "February": "Februar",
        "March": "März",
        "April": "April",
        "May": "Mai",
        "June": "Juni",
        "July": "Juli",
        "August": "August",
        "September": "September",
        "October": "Oktober",
        "November": "November",
        "December": "Dezember"
      } %}

      {% set aktuellesDatum = now() %} {{
      wochenTage[aktuellesDatum.strftime('%A')] }},  {{
      aktuellesDatum.strftime('%d') }}.  {{
      monate[aktuellesDatum.strftime('%B')] }}  {{ aktuellesDatum.strftime('%Y')
      }}
```

darunter könntest Du dann die another MVG Karte packen. Also als 3. Karte im Vertical Stack.
Wäre das eine Lösung ?

**Comment by Dekyi** [comment]
Ich dachte bisher an ein e-ink Display mit ESPhome aber jetzt finde ich die MVG Karte so hübsch und werde vielleicht auf ein PyPortal wechseln das hier noch rumliegt. Ich hätte jetzt gedacht das die Zeit oben rechtsbündig, also neben dem Stationsnamen, gut hinpassen würde und keine extra Zeile verbraucht. Aber das probiere ich dann mal aus.

**Comment by Nisbo** [comment]
Ich bastel gerade etwas

![grafik](https://github.com/user-attachments/assets/9af3b5b8-0cac-45e3-a730-5a3f068212b0)

Soll dann, wenn es so funktioniert wie ich es mir denke, per Option einblendbar sein.
Nutzt dann aber die Zeit vom Anzeigegerät wie dem Handy (App) oder dem Browser

**Comment by Dekyi** [comment]
Perfekt,genau das habe ich gemeint. Vielen Dank

**Comment by Nisbo** [comment]
Wenn Du testen möchtest, ich habe gerade eine BETA dazu released
https://github.com/Nisbo/another_mvg/releases/tag/v2.1.0.BETA.1

**Comment by Dekyi** [comment]
Die Beta funktoniert einwandfrei mit Safari und Firefox auf Desktop und iPhone.

**Comment by Nisbo** [comment]
Super, dass freut mich.
Und es gibt gleich noch eine neue BETA, falls Du testen möchtest
https://github.com/Nisbo/another_mvg/releases/tag/v2.1.0.BETA.2

**Comment by Dekyi** [comment]
Beta.2 funktioniert bei mir auch soweit.

**Comment by Nisbo** [comment]
Ups, hatte Deine Antwort vollkommen übersehen.
Dieses Problem hatte ich auch schon mal, k.A. warum es so ist.
Inzwischen ist 2.1.0 released und die Änderungen sind auch dort übernommen worden.
