### ISSUE TITLE
Fahrten werden nicht über einen Datumswechsel angezeigt

### ISSUE THREAD

**Issue by sektoderselters** [Nisbo/another_mvg#22]
Sehr schöne Arbeit!

Bei mir gibts es Probleme bei einer Abfahrtsanzeige über ein Datumswechsel.

So endet die Anzeige bei den Abfahrten am gleichen Tag, Fahrten am Folgetag fehlen.

Nach 00:00h werden wieder die Fahrten des „neuen“ Tag korrekt angezeigt.

**Comment by Nisbo** [comment]
Servus,

danke. :) 

Dieses Verhalten habe ich auch schon festgestellt. Die MVG API liefert diese Daten einfach nicht. Ich kann hier leider nichts machen. Zumindest ist mir dazu noch nichts eingefallen.

**Comment by Nisbo** [comment]
Ich habe gerade hier mal geschaut, geht auch auf deren Webseite nicht über Mitternacht hinaus.
https://www.mvg.de/meinhalt/eichenau-b-muenchen_eichenau

**Comment by Nisbo** [comment]
Ich habe eine Lösung gefunden. Diese ist möglicherweise nicht perfekt, insbesondere wenn man mit Filtern arbeitet, aber sie ist besser als keine Lösung.

### Funktionsweise
- Wenn die API **0 Einträge** liefert, frage ich zusätzlich ab Mitternacht erneut ab.
- Wenn die Anzahl der Einträge kleiner als das eingestellte Limit ist, frage ich ebenfalls zusätzlich ab Mitternacht ab und kombiniere die Abfahrten.

### Hinweise
1. **Zeitabhängigkeit**  
   Die Zeit auf dem Rechner, auf dem Home Assistant läuft, muss korrekt eingestellt sein, da ich mit einem Offset von der aktuellen Zeit bis Mitternacht arbeiten muss.

2. **Zusätzliche API-Abfragen**  
   Durch die zusätzliche Abfrage entsteht innerhalb kürzester Zeit eine weitere API-Abfrage. Dies erhöht das Risiko, dass die API blockiert wird.  
   Bei der Kombination von zwei Stationen entstehen sogar **vier Abfragen statt zwei**.

3. **Filtereinschränkungen**  
   Die Filter greifen erst nach der Abfrage. Wenn z. B. das Limit auf **10** eingestellt ist und die API **20 ungefilterte Einträge** liefert, wird keine zusätzliche Abfrage durchgeführt.  
   Das bedeutet, es können weniger Einträge angezeigt werden, als im Limit festgelegt.

---

Dies ist keine perfekte Lösung, aber sie stellt sicher, dass in den meisten Fällen sinnvolle Daten bereitgestellt werden.

**Comment by Nisbo** [comment]
BETA.5 released

https://github.com/Nisbo/another_mvg/releases/tag/v2.1.0.BETA.5

**Comment by Nisbo** [comment]
Included in 2.1.0
