### ISSUE TITLE
Custom element doesn't exist: content-card-another-mvg

### ISSUE THREAD

**Issue by oomastroo** [Nisbo/another_mvg#9]
I have read the previous issue and am now confused. Where exactly should the file be placed? In your installation you are not talking about how and where to place this file. Meanwhile, it is located in the "frontend" folder between other files. So where should I move the file "content-card-another-mvg" for your integration to work?

This is what I get, following your instructions:
![image](https://github.com/user-attachments/assets/a9bdb3f9-2f86-4bdc-acb3-f5f26e09104e)

**Comment by Nisbo** [comment]
In the past there was a different location for this file inside the www folder.
You are right, meanwhile its located in the frontend folder and this is the correct location if you are using v1.5.0.
Now the addon will register the cards by its own.
v1.5.0 was released today some hours ago.

- Which version are you using ? 
- When did you install Another MVG ?
- Do you have HACS ? Its easier to install with HACS

**Comment by oomastroo** [comment]
Hi, I am using v1.5.0 and installed it today, via HACS.

**Comment by Nisbo** [comment]
OK lets try to find the problem, maybe another_mvg is not loaded

- please post the code from your YAML 
- Is the entity "pasing" available ?
Settings —> Devices & Services —> Entities --> search mask --> enter: pasing
- anything in the log for another_mvg ?

What you can also try is clear the frontend cache (press CTRL+F5 in your browser)

**Comment by oomastroo** [comment]
well, CTRL+F5 solved the issue.👍 So basically everything was fine.
Thank you.
